# Generated by Django 5.0.6 on 2024-06-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='size_L',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='size_M',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='size_S',
            field=models.BooleanField(default=False),
        ),
    ]
